export const SEARCH_PLACES_API_REQUEST = 'SEARCH_PLACES_API_REQUEST';
export const PLACE_DETAILS_API_REQUEST = 'PLACE_DETAILS_API_REQUEST';
export const SEARCH_PLACES_API_SUCCESS = 'SEARCH_PLACES_API_SUCCESS';
export const PLACE_DETAILS_API_SUCCESS = 'PLACE_DETAILS_API_SUCCESS';
export const ERROR = 'ERROR';

export const ADD_PLACE_CLICK = 'ADD_PLACE_CLICK';
export const ADD_PLACE_REQUEST = 'ADD_PLACE_REQUEST';
export const ADD_PLACE_SUCCESS = 'ADD_PLACE_SUCCESS';
export const ADD_PLACE_FAILED = 'ADD_PLACE_FAILED';

export const REMOVE_PLACE_CLICK = 'REMOVE_PLACE_CLICK';
export const REMOVE_PLACE_REQUEST = 'REMOVE_PLACE_REQUEST';
export const REMOVE_PLACE_SUCCESS = 'REMOVE_PLACE_SUCCESS';
export const REMOVE_PLACE_FAILED = 'REMOVE_PLACE_FAILED';

export const UPDATE_PLACE_CLICK = 'UPDATE_PLACE_CLICK';
export const UPDATE_PLACE_REQUEST = 'UPDATE_PLACE_REQUEST';
export const UPDATE_PLACE_SUCCESS = 'UPDATE_PLACE_SUCCESS';
export const UPDATE_PLACE_FAILED = 'UPDATE_PLACE_FAILED';
